title: MCU couse
tagline: ESP32 Lectures

author:
  name: Richard Kuo
  url: https://www.facebook.com/richard.kuo.168

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 3

tags_path: /tags/
categories_path: /categories/

theme: jekyll-theme-cayman
